spring:
  email:
    host: outlook.office365.com
    port: 993
    username: assist@rekol.me
    password: MarblinaSquisher9
    properties:
      mail:
        store:
          protocol: imap
        imap:
          port: 993
          ssl:
            enable: true
          ssl.trust: "*"