email:
  host: outlook.office365.com
  port: 993
  username: assist@rekol.me
  password: MarblinaSquisher9
  protocol: imap
  ssl:
    enable: true
  properties:
    mail:
      store:
        protocol: imap
      imap:
        ssl:
          enable: true