plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.jml'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(23)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation 'com.icegreen:greenmail:2.0.1'
	implementation 'com.sun.mail:jakarta.mail:2.0.1'
	implementation 'org.springframework.integration:spring-integration-mail'
	implementation 'org.springframework.integration:spring-integration-core'
	implementation 'org.springframework.boot:spring-boot-starter-integration'
	implementation 'com.nimbusds:nimbus-jose-jwt:9.38'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation 'org.mockito:mockito-core:5.12.0'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'com.microsoft.graph:microsoft-graph:5.50.0'
	implementation 'com.azure:azure-identity:1.10.0'

}

tasks.named('test') {
	useJUnitPlatform()
}
